let g:airline_theme='papercolor'
let g:airline#extensions#whitespace#enabled = 1
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:airline_symbols = {}
let g:airline_symbols.linenr = ' '
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_section_a = ''
let g:airline_section_y = ''
let g:webdevicons_enable_airline_statusline_fileformat_symbols = 0
let g:airline_section_z = "%p%%|%l/%L|%c"
let g:airline_symbols.dirty = '  '
